language: python
sudo: required
dist: xenial
python:
- '2.7'
- '3.6'
- '3.7'
install: pip install tox-travis
script: tox
before_script:
- wget http://deb.hozac.com/dhozac/ubuntu/xenial/rethinkdb_2.3.6+15+g8a9687~0_amd64.deb
- "sudo dpkg -i ./rethinkdb_2.3.6+15+g8a9687~0_amd64.deb || :"
- sudo apt-get install -f -y
- sudo cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/instance1.conf
- sudo bash /etc/init.d/rethinkdb start
- while ! nc -z 127.0.0.1 28015; do sleep 1; done
env:
- HANDLE_COVERAGE=coveralls
deploy:
  provider: pypi
  username: dhozac
  password:
    secure: GBw0nU3Kyo/xQEaGVc8WjbMuLE+RRUQ1L3ZCXr1PnysK2wrPMmzLWmTyvu+2PyPHyfSfhOqL5huFXTv3r1fgI4d8fGOFWbpwHr8WnCdR6/ZXFYAtMBirVMe2vMMDboUw077oPDKyvZLj3AkI2uCxGEs2+vy6fKsXFVTOHHLHTVXgyhVJsFnEp4U6w122Iz+sqliOU/OU3rmftRYBhJlr3TGe69ZQycYF6e93H/69eV8xYbbCuV6zPOjwYwsYERL+ISbOIUHS07JPrzeVzXEVpwXs5397PbkxNjndqLxSPdXzsr9ruTJrDjpisJTJ5va2ITIkuxxZm9jtVNRWVda+8FyKVFIUUKv83UUQE7r0HTR9AvRiaRX1xv+OMPAO+83Zd2vt08pIoYaFKX4/0T3PoGayEeehGtdY1tdUyReZ1DuTHiD16WQswrEssjCskY6FpIbW68q4H5K8UEfw++GfZQyraTdbVch0cEbplLL7WNJOAT3WKaCSZJK0HO6lwujEBtqGsG9DxMgGdj/KvHoNbs8mDa6Ivolk4/u/QbRgYM3dayn4gNnHpplEX72jZjAU6xvgdPImj9Gnpzf+2JGs6hO0VEJz+WtUOY5bMw1WzIiLQYEnZay2KnB3tP0mkXOWtocgLk2IfHMliL2Jvxc6Xe6wXNsZyi1L4IYsAm+gYXw=
  skip_existing: true
  on:
    tags: true
